### ISSUE TITLE
Update existing frequency map

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#15]
A new table was added to the RTPS_Gap db (model_avg_freq) to be used to show existing frequency. The avg_freq field shows a 24 hour average weekday frequency in number of trips/hour. The symbology can remain the same using the following breaks: 0-1 = 61+, 1-2 = 31-60, 2-4 = 16-30, 4+ = 0-15.

**Comment by rbeatty1** [comment]
When you trigger a pop-up that has multiple lines, switching between pop-ups refers to the old content and still needs to be fixed.
