### ISSUE TITLE
Add one sentence to remind people about different layers in reliability

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#26]
To save people from going back to the about tab (GK). This could also be a tool tip that you see when you hover? We can brainstorm more about this too. I will provide text soon.

**Comment by smoran3** [comment]
Reliability Score: A high reliability score is indicative of segments that may benefit from targeted improvements to improve transit operations.

Ridership Weighted Reliability Score: A high score indicates segments with a high potential for reliability issues that impact high ridership surface transit.

Average Speed by Line: Scheduled speed calculated from GTFS.

On Time Performance: Percent of time the bus arrives between 0 and 6 minutes after the scheduled time.

Travel Time Index: Ratio of peak hour travel time to free flow travel time. High TTI indicates congestion.

New Jersey Transit Ridership: Route level ridership from 2016-2017

SEPTA Passenger Loads (when added): Average daily passenger load calculated from 2017 stop level ridership.

_Also - can we change the colors of the text for 'Result' vs 'Input' in the layers list?_

**Comment by rbeatty1** [comment]
I'd like to discuss this a little more at our meeting. It's ready to go, I just haven't pushed it to the staging site. I have some thoughts but we can talk through them in person

**Comment by rbeatty1** [comment]
For note keeping purposes:
- [ ] Make layers default active tab
- [ ] Route filter moves to separate section than layer controls
- [ ] Description of active layer(s) at bottom of the layer control section 
- [ ] @smoran3 establish hierarchy for purpose/inputs/outputs in about section
