### ISSUE TITLE
Increase transparency of teal (not served) colors in Network gap map

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#28]
This one needs to fade while the oranges need to stand out. If they currently have the same transparency applied, they should be changed so the teal is much more transparent than the oranges.

**Comment by rbeatty1** [comment]
We can work through this in our meeting tomorrow. Easy to adjust

**Comment by smoran3** [comment]
that sounds like a super efficient way to fix it because all the right people will be in the room! thanks!
