### ISSUE TITLE
Reliability text and panel layout udpates

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#34]
Lets think/talk about this one more together. The idea would be to have the filter at the top of this new panel. You select your route(s) and then turn on the layers you want. The septa passenger loads would only be available on this panel since looking at the regional layer only shows what is on top. The regional layer panel would need a name...

**Comment by smoran3** [comment]
I did this a while ago, but I think I forgot to add it in here. I outlined all 3 tabs and included some text updates (as well as the single sentence reminders from issue #26 ) in the google doc in the reliability section.

**Comment by rbeatty1** [comment]
Closed with c8c1112
