### ISSUE TITLE
consider shifting demand filter in gap results

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#35]
Another one for us to think about together. When running tests for Upper Merion we realized that it looks like there is no demand from NJ. In reality, we know that's not true. The demand filter was used to reduce noise, but if someone interprets the map to mean that there is no one going from NJ to the KoP area, it will make people question the results. There could be a way to present this (as a screening tool focusing on the places with the most potential), or there could be a happy medium of demand filters to reduce noise but show more places at the same time. Of those that get filtered out (demand < 1), about 7% have demand between 0.5 and 1. That probably wouldn't add much. Lets test some queries when we meet and decide together.

**Comment by rbeatty1** [comment]
@smoran3 closing this for now based on this morning's discussion. We can reopen if we deem it necessary later on
