### ISSUE TITLE
Landing page feedback

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#58]
Looks fantastic! I know it's a work in progress, but just a few things I wanted to make note of:
- [x] Can there be more space at the top/bottom of the circles? On my laptop screen, it looks pretty squished.
- [x] Can we make it so if you click on the RTPP logo at the top, it goes back to the original look of the landing page with the question and gray background?
- [x] Not sure if it's just on my laptop screen, but when I click on a circle, learn more and explore are partially hidden behind the circles
- [ ] We need to add the link to policies, the contact, etc, that we talked about at DIT yesterday
- [x] On the individual maps, the top circles look a bit squished (horizontally) on my screen. Is there a way to get a little bit of the horizontal blue line between them, like on the landing page.

**Comment by rbeatty1** [comment]
I'm going to skip over #4 for now because I'm planning on overhauling the footer in general after the discussions from DIT and I'll address that bullet point with that update.
